import { InMemoryDbService } from 'angular-in-memory-web-api'; 
 
export class InMemoryDataService implements InMemoryDbService { 
  createDb() { 
    let items = [
      {"id":0,"name":"Tragedy Mask","caption":"Wooden Mask from Japan - Item 1/2 of a set","description":"The face of tragedy, which is part of a two-piece set of Japanese wooden masks. Dark wood, with ivory teeth. Given to me by my parents.","narratives":["A Mask Memory: I remember the time that Mom lit the mask with a flashlight for Halloween. She set it up on a table in a dark room, just waiting for us to return after trick or treating. I think I was twelve years old and you were nine. We had a giant bag filled with candy. When we opened the door, the light switch didn’t work, which seemed really odd. \n\nI stepped into the room and you hung behind me. We were both a little creeped \tout. Then I saw the mask sitting on the table, uplit and really scary looking. \n\nI screamed and you did, too. Then Mom turned on the light and jumped out. She was wearing a purple wig and makeup – she looked like Elvira – mistress of the dark!", "This is another narrative. It has to be long enough to take up space on the page so that the narratives can shrink when not selected."],"tags":["Japan","ERH Mom and Dad","Keep"],"imageUrls":["TragedyMask.jpg"]},
      {"id":1,"name":"Comedy mask","caption":"Wooden Mask from Japan - Item 2/2 from a set","description":"The face of comedy, which is part of a two-piece set of Japanese wooden masks. Dark wood, with ivory teeth. Given to me by my parents.","narratives":[],"tags":["Japan","ERH Mom and Dad","Keep"],"imageUrls":[]},
      {"id":2,"name":"Harpsichord","caption":"Flemish single built from a Zuckermann kit","description":"A Zuckermann Flemish single kit harpsichord built by ERH's Dad to celebrate her graduation from college (in 1978)! The kit was largely completed when the instrument travelled from Los Angeles to Boston in 1989. The harpsichord builder Dale Munschy built the voicing and completed the instrument in 2015. ","narratives":[],"tags":["Alan R Hoffer","musical instrument","keep"],"imageUrls":["Harpsichord.jpg"]},
      {"id":3,"name":"Tajine","caption":"Yellow ceramic cookware","description":"Purchased at the MFA in 2014. Great for cooking moroccan dishes on the stove or in the oven. The conical lid is supposed to provide the right amount of condensation for couscous. Goes with the recipes of Ottolenghi or Paula Wolfert.","narratives":[],"tags":["cookware","dining room","donate"],"imageUrls":["Tajine.jpg"]},
      {"id":4,"name":"Woman in the Wind","caption":"A framed painting done by a friend, Tami Wicinas","description":"From the artist Tami Wicinas, niece of our friend Dave Wicinas. We purchased the art from her in 2013 and framed it. Tami lives in San Francisco. She is a graphic designer and artist who publishes graphic novels.","narratives":[],"tags":["piano alcove","original art","Wicinas"],"imageUrls":["WomanWind.jpg"]},
      {"id":5,"name":"Gray candlesticks (2)","caption":"A pair of wooden painted candleholders","description":"Purchased at the Hourglass craft shop in 2013. ","narratives":[],"tags":["sell","dining room"],"imageUrls":["Candlesticks-2.jpg"]},
      {"id":6,"name":"Political Art","caption":"Sculpture made from books of conservative political figures","description":"A progressive gift which started in 2012 when Bruce ended up (unhappily) with the 2010 book by Sarah Palin, \"American by Heart\" at the Wilson Butler holiday yankee swap. He modified the book by running a bolt through it and gifted it to Jack Green. The following year, Jack attached \"Against All Odds\" by Scott Brown, added a stand and regifted the assembly to Bruce. In 2014, Bruce added \"Arguing with Idiots\" by Glenn Beck. In 2015, Jack added \"Crippled America\" by Donald J. Trump. In 2016, Bruce illuminated the construction, adding glowing red eyes to the Trump cover, and regifting it back to Jack. He turned the book into a Collectible, although we didn't know it until Nov 9, 2016. In May 2017, the Greens downsized and sold their Boston home, and the sculpture was given to the Wicinas family.","narratives":[],"tags":["political art","Wicinas"],"imageUrls":["PoliticalArt.jpg"]},
      {"id":7,"name":"Candlesticks (multiple brass)","caption":"A set of fifty brass candlesticks - misc shapes and sizes","description":"On Bruce's fiftieth birthday, he wanted to go on a camping trip so we did a group trip out to Tully Lake. A bunch of us met for a lovely weekend on the water. Bruce got a large sized paella pan for his birthday, so we made a giant paella for dinner. His friends contributed seafood and a delicious coconut cake! I got fifty candlesticks at good prices on ebay and set them all around the campsite. Then B's friends gave him a kayak! The next day we enjoyed going around on the water in the new boat.","narratives":[],"tags":["tableware","Bruce's 50th","donate"],"imageUrls":["Candlesticks-manybrass.jpg"]},
      {"id":8,"name":"Dog Toy","caption":"A squeaky toy for a pet","description":"Bought on Amazon. Our dog Lacey loved it! ","narratives":[],"tags":["toy","dog"],"imageUrls":["DogToy.jpg"]},
      {"id":9,"name":"Blue sock monkey","caption":"Part of a collection of sock monkeys from Barb","description":"A few years ago, Bruce and Barb started exchanging sock monkeys as gifts. This blue one was from 2013 (?). It is very photogenic.","narratives":[],"tags":["sock monkey","Barb","toy"],"imageUrls":["BlueSockMonkey.jpg"]},
      {"id":10,"name":"Kawai Piano","caption":"A black upright piano","description":"This instrument was purchased at a sale at the New England Conservatory when the kids were young. 1992? Zach used the piano as he learned to play through the Suzuki program, then with private teachers until he finished high school. The piano is in good condition. ","narratives":[],"tags":["musical instrument","sell","piano alcove"],"imageUrls":["Piano.jpg"]},
      {"id":11,"name":"Borkin Vase","caption":"An artist glass vase in green, gold and dark blue","description":"This vase is one of two matching glass artworks done by Gary Borkin on Melrose. We won both pieces in a raffle at the annual Melrose Arts and Crafts fair in 2014. When we went to pick up the pieces we went to Gary's house and had a lovely visit as he told us about how he got into glass art and showed some of his other pieces. He is very involved in the Melrose Art scene, which is pretty active, since we have many local artists.","narratives":[],"tags":["dining room","Gary Borkin","original art"],"imageUrls":["GreenVase.jpg"]},
      {"id":12,"name":"\"Heart\" calligraphy","caption":"Original work by Shotei Ibata","description":"A piece by calligraphy artist Shotei Ibata, from Kyoto Japan. Purchased by \nAlan and Shirley Ann Hoffer when they were living in Japan for a sabbatical year (1994?)\nhttp://japanlivingarts.com/shotei-ibata-sensei-moving-calligraphy-into-the-21st-century/ ","narratives":[],"tags":["Japan","Alan and Shirley Ann","original art"],"imageUrls":["SI-Heart.jpg"]},
      {"id":13,"name":"Nolli Map","caption":"Framed twelve panel prints which form a map of Rome","description":"These twelve prints are replicas of an engraved map of Rome done by Giambattista Nolli in the 1600s. We purchased the set from LA Prints around 1980 before relocating to the Boston area to commemorate our year abroad in the town of Ronciglione with other students and Professor Robert Mangurian. \nhttps://en.wikipedia.org/wiki/Giambattista_Nolli","narratives":[],"tags":["Italy","original art","bedroom"],"imageUrls":[]},
      {"id":14,"name":"Antique wood frame mirror","caption":"An antique mirror framed in wood","description":"This mirror was from the estate of Margaret Herrmann, Bruce's mom. He brought it back from Ohio on one of our visits. He used to bring a trailer on the 12 hour drive to Columbiana so he could collect memorabilia and family objects. There are many other objects - an old antique bicycle, loveseat, captain's chairs.","narratives":[],"tags":["Margaret","front hall"],"imageUrls":[]}
    ]; 
    let stories = [ 
      {"id":0,"name":"Clara and Richard Nishimoto History","caption":"Two first-generation citizens start a family in Hawaii during turbulent times.","description":"Richard Nishimoto and Clara Kuraoka met in Honolulu.They were introduced by a mutual friend and married in 1934.They had three children, Shirley Ann in 1935, Jean in 1940, and Warren in 1942.They lived at 2819 Keama Place in the Manoa Valley for 50 years.","item_ids":[0]}
    ]; 
    return { items, stories }; 
  } 
}
